import { Injectable } from '@angular/core';
import parsePhoneNumber from 'libphonenumber-js';

@Injectable({
  providedIn: 'root',
})
export class CountriesService {
  constructor() {}

  list: any[] = [
    {
      name: 'Afghanistan',
      code: 'AF',
      dial_code: '+93',
      city: 'Kabul',
      continent: 'Asia',
    },
    {
      name: 'Albania',
      code: 'AL',
      dial_code: '+355',
      city: 'Tirana',
      continent: 'Europe',
    },
    {
      name: 'Algeria',
      code: 'DZ',
      dial_code: '+213',
      city: 'Alger',
      continent: 'Africa',
    },
    {
      name: 'American Samoa',
      code: 'AS',
      dial_code: '+1684',
      city: 'Fagatogo',
      continent: 'Oceania',
    },
    {
      name: 'Andorra',
      code: 'AD',
      dial_code: '+376',
      city: 'Andorra la Vella',
      continent: 'Europe',
    },
    {
      name: 'Angola',
      code: 'AO',
      dial_code: '+244',
      city: 'Luanda',
      continent: 'Africa',
    },
    {
      name: 'Anguilla',
      code: 'AI',
      dial_code: '+1264',
      city: 'The Valley',
      continent: 'North America',
    },
    {
      name: 'Antarctica',
      code: 'AQ',
      dial_code: '+672',
      city: '',
      continent: 'Antarctica',
    },
    {
      name: 'Antigua and Barbuda',
      code: 'AG',
      dial_code: '+1268',
      city: "Saint John's",
      continent: 'North America',
    },
    {
      name: 'Argentina',
      code: 'AR',
      dial_code: '+54',
      city: 'Buenos Aires',
      continent: 'South America',
    },
    {
      name: 'Armenia',
      code: 'AM',
      dial_code: '+374',
      city: 'Yerevan',
      continent: 'Asia',
    },
    {
      name: 'Aruba',
      code: 'AW',
      dial_code: '+297',
      city: 'Oranjestad',
      continent: 'North America',
    },
    {
      name: 'Australia',
      code: 'AU',
      dial_code: '+61',
      city: 'Canberra',
      continent: 'Oceania',
    },
    {
      name: 'Austria',
      code: 'AT',
      dial_code: '+43',
      city: 'Wien',
      continent: 'Europe',
    },
    {
      name: 'Azerbaijan',
      code: 'AZ',
      dial_code: '+994',
      city: 'Baku',
      continent: 'Asia',
    },
    {
      name: 'Bahamas',
      code: 'BS',
      dial_code: '+1242',
      city: 'Nassau',
      continent: 'North America',
    },
    {
      name: 'Bahrain',
      code: 'BH',
      dial_code: '+973',
      city: 'al-Manama',
      continent: 'Asia',
    },
    {
      name: 'Bangladesh',
      code: 'BD',
      dial_code: '+880',
      city: 'Dhaka',
      continent: 'Asia',
    },
    {
      name: 'Barbados',
      code: 'BB',
      dial_code: '+1246',
      city: 'Bridgetown',
      continent: 'North America',
    },
    {
      name: 'Belarus',
      code: 'BY',
      dial_code: '+375',
      city: 'Minsk',
      continent: 'Europe',
    },
    {
      name: 'Belgium',
      code: 'BE',
      dial_code: '+32',
      city: 'Bruxelles [Brussel]',
      continent: 'Europe',
    },
    {
      name: 'Belize',
      code: 'BZ',
      dial_code: '+501',
      city: 'Belmopan',
      continent: 'North America',
    },
    {
      name: 'Benin',
      code: 'BJ',
      dial_code: '+229',
      city: 'Porto-Novo',
      continent: 'Africa',
    },
    {
      name: 'Bermuda',
      code: 'BM',
      dial_code: '+1441',
      city: 'Hamilton',
      continent: 'North America',
    },
    {
      name: 'Bhutan',
      code: 'BT',
      dial_code: '+975',
      city: 'Thimphu',
      continent: 'Asia',
    },
    {
      name: 'Bolivia',
      code: 'BO',
      dial_code: '+591',
      city: 'La Paz',
      continent: 'South America',
    },
    {
      name: 'Bosnia and Herzegovina',
      code: 'BA',
      dial_code: '+387',
      city: 'Sarajevo',
      continent: 'Europe',
    },
    {
      name: 'Botswana',
      code: 'BW',
      dial_code: '+267',
      city: 'Gaborone',
      continent: 'Africa',
    },
    {
      name: 'Bouvet Island',
      code: 'BV',
      dial_code: '+55',
      city: '',
      continent: 'Antarctica',
    },
    {
      name: 'Brazil',
      code: 'BR',
      dial_code: '+55',
      city: 'Brasília',
      continent: 'South America',
    },
    {
      name: 'British Indian Ocean Territory',
      code: 'IO',
      dial_code: '+246',
      city: '',
      continent: 'Africa',
    },
    {
      name: 'Brunei',
      code: 'BN',
      dial_code: '+673',
      city: 'Bandar Seri Begawan',
      continent: 'Asia',
    },
    {
      name: 'Bulgaria',
      code: 'BG',
      dial_code: '+359',
      city: 'Sofia',
      continent: 'Europe',
    },
    {
      name: 'Burkina Faso',
      code: 'BF',
      dial_code: '+226',
      city: 'Ouagadougou',
      continent: 'Africa',
    },
    {
      name: 'Burundi',
      code: 'BI',
      dial_code: '+257',
      city: 'Bujumbura',
      continent: 'Africa',
    },
    {
      name: 'Cambodia',
      code: 'KH',
      dial_code: '+855',
      city: 'Phnom Penh',
      continent: 'Asia',
    },
    {
      name: 'Cameroon',
      code: 'CM',
      dial_code: '+237',
      city: 'Yaound',
      continent: 'Africa',
    },
    {
      name: 'Canada',
      code: 'CA',
      dial_code: '+1',
      city: 'Ottawa',
      continent: 'North America',
    },
    {
      name: 'Cape Verde',
      code: 'CV',
      dial_code: '+238',
      city: 'Praia',
      continent: 'Africa',
    },
    {
      name: 'Cayman Islands',
      code: 'KY',
      dial_code: '+1345',
      city: 'George Town',
      continent: 'North America',
    },
    {
      name: 'Central African Republic',
      code: 'CF',
      dial_code: '+236',
      city: 'Bangui',
      continent: 'Africa',
    },
    {
      name: 'Chad',
      code: 'TD',
      dial_code: '+235',
      city: "N'Djam",
      continent: 'Africa',
    },
    {
      name: 'Chile',
      code: 'CL',
      dial_code: '+56',
      city: 'Santiago de Chile',
      continent: 'South America',
    },
    {
      name: 'China',
      code: 'CN',
      dial_code: '+86',
      city: 'Peking',
      continent: 'Asia',
    },
    {
      name: 'Christmas Island',
      code: 'CX',
      dial_code: '+61',
      city: 'Flying Fish Cove',
      continent: 'Oceania',
    },
    {
      name: 'Cocos (Keeling) Islands',
      code: 'CC',
      dial_code: '+61',
      city: 'West Island',
      continent: 'Oceania',
    },
    {
      name: 'Colombia',
      code: 'CO',
      dial_code: '+57',
      city: 'Santaf',
      continent: 'South America',
    },
    {
      name: 'Comoros',
      code: 'KM',
      dial_code: '+269',
      city: 'Moroni',
      continent: 'Africa',
    },
    {
      name: 'Congo',
      code: 'CG',
      dial_code: '+242',
      city: 'Brazzaville',
      continent: 'Africa',
    },
    {
      name: 'Cook Islands',
      code: 'CK',
      dial_code: '+682',
      city: 'Avarua',
      continent: 'Oceania',
    },
    {
      name: 'Costa Rica',
      code: 'CR',
      dial_code: '+506',
      city: 'San Jos',
      continent: 'North America',
    },
    {
      name: 'Croatia',
      code: 'HR',
      dial_code: '+385',
      city: 'Zagreb',
      continent: 'Europe',
    },
    {
      name: 'Cuba',
      code: 'CU',
      dial_code: '+53',
      city: 'La Habana',
      continent: 'North America',
    },
    {
      name: 'Cyprus',
      code: 'CY',
      dial_code: '+357',
      city: 'Nicosia',
      continent: 'Asia',
    },
    {
      name: 'Czech Republic',
      code: 'CZ',
      dial_code: '+420',
      city: 'Praha',
      continent: 'Europe',
    },
    {
      name: 'Denmark',
      code: 'DK',
      dial_code: '+45',
      city: 'Copenhagen',
      continent: 'Europe',
    },
    {
      name: 'Djibouti',
      code: 'DJ',
      dial_code: '+253',
      city: 'Djibouti',
      continent: 'Africa',
    },
    {
      name: 'Dominica',
      code: 'DM',
      dial_code: '+1767',
      city: 'Roseau',
      continent: 'North America',
    },
    {
      name: 'Dominican Republic',
      code: 'DO',
      dial_code: '+1849',
      city: 'Santo Domingo de Guzm',
      continent: 'North America',
    },
    {
      name: 'East Timor',
      code: 'TP',
      dial_code: '+670',
      city: 'Dili',
      continent: 'Asia',
    },
    {
      name: 'Ecuador',
      code: 'EC',
      dial_code: '+593',
      city: 'Quito',
      continent: 'South America',
    },
    {
      name: 'Egypt',
      code: 'EG',
      dial_code: '+20',
      city: 'Cairo',
      continent: 'Africa',
    },
    {
      name: 'El Salvador',
      code: 'SV',
      dial_code: '+503',
      city: 'San Salvador',
      continent: 'North America',
    },
    {
      name: 'Equatorial Guinea',
      code: 'GQ',
      dial_code: '+240',
      city: 'Malabo',
      continent: 'Africa',
    },
    {
      name: 'Eritrea',
      code: 'ER',
      dial_code: '+291',
      city: 'Asmara',
      continent: 'Africa',
    },
    {
      name: 'Estonia',
      code: 'EE',
      dial_code: '+372',
      city: 'Tallinn',
      continent: 'Europe',
    },
    {
      name: 'Ethiopia',
      code: 'ET',
      dial_code: '+251',
      city: 'Addis Abeba',
      continent: 'Africa',
    },
    {
      name: 'Falkland Islands',
      code: 'FK',
      dial_code: '+500',
      city: 'Stanley',
      continent: 'South America',
    },
    {
      name: 'Faroe Islands',
      code: 'FO',
      dial_code: '+298',
      city: 'Tórshavn',
      continent: 'Europe',
    },
    {
      name: 'Fiji Islands',
      code: 'FJ',
      dial_code: '+679',
      city: 'Suva',
      continent: 'Oceania',
    },
    {
      name: 'Finland',
      code: 'FI',
      dial_code: '+358',
      city: 'Helsinki [Helsingfors]',
      continent: 'Europe',
    },
    {
      name: 'France',
      code: 'FR',
      dial_code: '+33',
      city: 'Paris',
      continent: 'Europe',
    },
    {
      name: 'French Guiana',
      code: 'GF',
      dial_code: '+594',
      city: 'Cayenne',
      continent: 'South America',
    },
    {
      name: 'French Polynesia',
      code: 'PF',
      dial_code: '+689',
      city: 'Papeete',
      continent: 'Oceania',
    },
    {
      name: 'French Southern territories',
      code: 'TF',
      dial_code: '+262',
      city: '',
      continent: 'Antarctica',
    },
    {
      name: 'Gabon',
      code: 'GA',
      dial_code: '+241',
      city: 'Libreville',
      continent: 'Africa',
    },
    {
      name: 'Gambia',
      code: 'GM',
      dial_code: '+220',
      city: 'Banjul',
      continent: 'Africa',
    },
    {
      name: 'Georgia',
      code: 'GE',
      dial_code: '+995',
      city: 'Tbilisi',
      continent: 'Asia',
    },
    {
      name: 'Germany',
      code: 'DE',
      dial_code: '+49',
      city: 'Berlin',
      continent: 'Europe',
    },
    {
      name: 'Ghana',
      code: 'GH',
      dial_code: '+233',
      city: 'Accra',
      continent: 'Africa',
    },
    {
      name: 'Gibraltar',
      code: 'GI',
      dial_code: '+350',
      city: 'Gibraltar',
      continent: 'Europe',
    },
    {
      name: 'Greece',
      code: 'GR',
      dial_code: '+30',
      city: 'Athenai',
      continent: 'Europe',
    },
    {
      name: 'Greenland',
      code: 'GL',
      dial_code: '+299',
      city: 'Nuuk',
      continent: 'North America',
    },
    {
      name: 'Grenada',
      code: 'GD',
      dial_code: '+1473',
      city: "Saint George's",
      continent: 'North America',
    },
    {
      name: 'Guadeloupe',
      code: 'GP',
      dial_code: '+590',
      city: 'Basse-Terre',
      continent: 'North America',
    },
    {
      name: 'Guam',
      code: 'GU',
      dial_code: '+1671',
      city: 'Aga',
      continent: 'Oceania',
    },
    {
      name: 'Guatemala',
      code: 'GT',
      dial_code: '+502',
      city: 'Ciudad de Guatemala',
      continent: 'North America',
    },
    {
      name: 'Guernsey',
      code: 'GG',
      dial_code: '+undefined',
    },
    {
      name: 'Guinea',
      code: 'GN',
      dial_code: '+224',
      city: 'Conakry',
      continent: 'Africa',
    },
    {
      name: 'Guinea-Bissau',
      code: 'GW',
      dial_code: '+245',
      city: 'Bissau',
      continent: 'Africa',
    },
    {
      name: 'Guyana',
      code: 'GY',
      dial_code: '+592',
      city: 'Georgetown',
      continent: 'South America',
    },
    {
      name: 'Haiti',
      code: 'HT',
      dial_code: '+509',
      city: 'Port-au-Prince',
      continent: 'North America',
    },
    {
      name: 'Heard Island and McDonald Islands',
      code: 'HM',
      dial_code: '+672',
      city: '',
      continent: 'Antarctica',
    },
    {
      name: 'Holy See (Vatican City State)',
      code: 'VA',
      dial_code: '+379',
      city: 'Citt',
      continent: 'Europe',
    },
    {
      name: 'Honduras',
      code: 'HN',
      dial_code: '+504',
      city: 'Tegucigalpa',
      continent: 'North America',
    },
    {
      name: 'Hong Kong',
      code: 'HK',
      dial_code: '+852',
      city: 'Victoria',
      continent: 'Asia',
    },
    {
      name: 'Hungary',
      code: 'HU',
      dial_code: '+36',
      city: 'Budapest',
      continent: 'Europe',
    },
    {
      name: 'Iceland',
      code: 'IS',
      dial_code: '+354',
      city: 'Reykjav',
      continent: 'Europe',
    },
    {
      name: 'India',
      code: 'IN',
      dial_code: '+91',
      city: 'New Delhi',
      continent: 'Asia',
    },
    {
      name: 'Indonesia',
      code: 'ID',
      dial_code: '+62',
      city: 'Jakarta',
      continent: 'Asia',
    },
    {
      name: 'Iran',
      code: 'IR',
      dial_code: '+98',
      city: 'Tehran',
      continent: 'Asia',
    },
    {
      name: 'Iraq',
      code: 'IQ',
      dial_code: '+964',
      city: 'Baghdad',
      continent: 'Asia',
    },
    {
      name: 'Ireland',
      code: 'IE',
      dial_code: '+353',
      city: 'Dublin',
      continent: 'Europe',
    },
    {
      name: 'Isle of Man',
      code: 'IM',
      dial_code: '+undefined',
    },
    {
      name: 'Israel',
      code: 'IL',
      dial_code: '+972',
      city: 'Jerusalem',
      continent: 'Asia',
    },
    {
      name: 'Italy',
      code: 'IT',
      dial_code: '+39',
      city: 'Roma',
      continent: 'Europe',
    },
    {
      name: 'Ivory Coast',
      code: 'CI',
      dial_code: '+225',
      city: 'Yamoussoukro',
      continent: 'Africa',
    },
    {
      name: 'Jamaica',
      code: 'JM',
      dial_code: '+1876',
      city: 'Kingston',
      continent: 'North America',
    },
    {
      name: 'Japan',
      code: 'JP',
      dial_code: '+81',
      city: 'Tokyo',
      continent: 'Asia',
    },
    {
      name: 'Jersey',
      code: 'JE',
      dial_code: '+undefined',
    },
    {
      name: 'Jordan',
      code: 'JO',
      dial_code: '+962',
      city: 'Amman',
      continent: 'Asia',
    },
    {
      name: 'Kazakhstan',
      code: 'KZ',
      dial_code: '+7',
      city: 'Astana',
      continent: 'Asia',
    },
    {
      name: 'Kenya',
      code: 'KE',
      dial_code: '+254',
      city: 'Nairobi',
      continent: 'Africa',
    },
    {
      name: 'Kiribati',
      code: 'KI',
      dial_code: '+686',
      city: 'Bairiki',
      continent: 'Oceania',
    },
    {
      name: 'Kuwait',
      code: 'KW',
      dial_code: '+965',
      city: 'Kuwait',
      continent: 'Asia',
    },
    {
      name: 'Kyrgyzstan',
      code: 'KG',
      dial_code: '+996',
      city: 'Bishkek',
      continent: 'Asia',
    },
    {
      name: 'Laos',
      code: 'LA',
      dial_code: '+856',
      city: 'Vientiane',
      continent: 'Asia',
    },
    {
      name: 'Latvia',
      code: 'LV',
      dial_code: '+371',
      city: 'Riga',
      continent: 'Europe',
    },
    {
      name: 'Lebanon',
      code: 'LB',
      dial_code: '+961',
      city: 'Beirut',
      continent: 'Asia',
    },
    {
      name: 'Lesotho',
      code: 'LS',
      dial_code: '+266',
      city: 'Maseru',
      continent: 'Africa',
    },
    {
      name: 'Liberia',
      code: 'LR',
      dial_code: '+231',
      city: 'Monrovia',
      continent: 'Africa',
    },
    {
      name: 'Libyan Arab Jamahiriya',
      code: 'LY',
      dial_code: '+218',
      city: 'Tripoli',
      continent: 'Africa',
    },
    {
      name: 'Liechtenstein',
      code: 'LI',
      dial_code: '+423',
      city: 'Vaduz',
      continent: 'Europe',
    },
    {
      name: 'Lithuania',
      code: 'LT',
      dial_code: '+370',
      city: 'Vilnius',
      continent: 'Europe',
    },
    {
      name: 'Luxembourg',
      code: 'LU',
      dial_code: '+352',
      city: 'Luxembourg [Luxemburg/L',
      continent: 'Europe',
    },
    {
      name: 'Macao',
      code: 'MO',
      dial_code: '+853',
      city: 'Macao',
      continent: 'Asia',
    },
    {
      name: 'North Macedonia',
      code: 'MK',
      dial_code: '+389',
      city: 'Skopje',
      continent: 'Europe',
    },
    {
      name: 'Madagascar',
      code: 'MG',
      dial_code: '+261',
      city: 'Antananarivo',
      continent: 'Africa',
    },
    {
      name: 'Malawi',
      code: 'MW',
      dial_code: '+265',
      city: 'Lilongwe',
      continent: 'Africa',
    },
    {
      name: 'Malaysia',
      code: 'MY',
      dial_code: '+60',
      city: 'Kuala Lumpur',
      continent: 'Asia',
    },
    {
      name: 'Maldives',
      code: 'MV',
      dial_code: '+960',
      city: 'Male',
      continent: 'Asia',
    },
    {
      name: 'Mali',
      code: 'ML',
      dial_code: '+223',
      city: 'Bamako',
      continent: 'Africa',
    },
    {
      name: 'Malta',
      code: 'MT',
      dial_code: '+356',
      city: 'Valletta',
      continent: 'Europe',
    },
    {
      name: 'Marshall Islands',
      code: 'MH',
      dial_code: '+692',
      city: 'Dalap-Uliga-Darrit',
      continent: 'Oceania',
    },
    {
      name: 'Martinique',
      code: 'MQ',
      dial_code: '+596',
      city: 'Fort-de-France',
      continent: 'North America',
    },
    {
      name: 'Mauritania',
      code: 'MR',
      dial_code: '+222',
      city: 'Nouakchott',
      continent: 'Africa',
    },
    {
      name: 'Mauritius',
      code: 'MU',
      dial_code: '+230',
      city: 'Port-Louis',
      continent: 'Africa',
    },
    {
      name: 'Mayotte',
      code: 'YT',
      dial_code: '+262',
      city: 'Mamoutzou',
      continent: 'Africa',
    },
    {
      name: 'Mexico',
      code: 'MX',
      dial_code: '+52',
      city: 'Ciudad de M',
      continent: 'North America',
    },
    {
      name: 'Micronesia, Federated States of',
      code: 'FM',
      dial_code: '+691',
      city: 'Palikir',
      continent: 'Oceania',
    },
    {
      name: 'Moldova',
      code: 'MD',
      dial_code: '+373',
      city: 'Chisinau',
      continent: 'Europe',
    },
    {
      name: 'Monaco',
      code: 'MC',
      dial_code: '+377',
      city: 'Monaco-Ville',
      continent: 'Europe',
    },
    {
      name: 'Mongolia',
      code: 'MN',
      dial_code: '+976',
      city: 'Ulan Bator',
      continent: 'Asia',
    },
    {
      name: 'Montenegro',
      code: 'ME',
      dial_code: '+undefined',
      city: 'Podgorica',
      continent: 'Europe',
    },
    {
      name: 'Montserrat',
      code: 'MS',
      dial_code: '+1664',
      city: 'Plymouth',
      continent: 'North America',
    },
    {
      name: 'Morocco',
      code: 'MA',
      dial_code: '+212',
      city: 'Rabat',
      continent: 'Africa',
    },
    {
      name: 'Mozambique',
      code: 'MZ',
      dial_code: '+258',
      city: 'Maputo',
      continent: 'Africa',
    },
    {
      name: 'Myanmar',
      code: 'MM',
      dial_code: '+95',
      city: 'Rangoon (Yangon)',
      continent: 'Asia',
    },
    {
      name: 'Namibia',
      code: 'NA',
      dial_code: '+264',
      city: 'Windhoek',
      continent: 'Africa',
    },
    {
      name: 'Nauru',
      code: 'NR',
      dial_code: '+674',
      city: 'Yaren',
      continent: 'Oceania',
    },
    {
      name: 'Nepal',
      code: 'NP',
      dial_code: '+977',
      city: 'Kathmandu',
      continent: 'Asia',
    },
    {
      name: 'Netherlands',
      code: 'NL',
      dial_code: '+31',
      city: 'Amsterdam',
      continent: 'Europe',
    },
    {
      name: 'Netherlands Antilles',
      code: 'AN',
      dial_code: '+599',
      city: 'Willemstad',
      continent: 'North America',
    },
    {
      name: 'New Caledonia',
      code: 'NC',
      dial_code: '+687',
      city: 'Noum',
      continent: 'Oceania',
    },
    {
      name: 'New Zealand',
      code: 'NZ',
      dial_code: '+64',
      city: 'Wellington',
      continent: 'Oceania',
    },
    {
      name: 'Nicaragua',
      code: 'NI',
      dial_code: '+505',
      city: 'Managua',
      continent: 'North America',
    },
    {
      name: 'Niger',
      code: 'NE',
      dial_code: '+227',
      city: 'Niamey',
      continent: 'Africa',
    },
    {
      name: 'Nigeria',
      code: 'NG',
      dial_code: '+234',
      city: 'Abuja',
      continent: 'Africa',
    },
    {
      name: 'Niue',
      code: 'NU',
      dial_code: '+683',
      city: 'Alofi',
      continent: 'Oceania',
    },
    {
      name: 'Norfolk Island',
      code: 'NF',
      dial_code: '+672',
      city: 'Kingston',
      continent: 'Oceania',
    },
    {
      name: 'North Korea',
      code: 'KP',
      dial_code: '+850',
      city: 'Pyongyang',
      continent: 'Asia',
    },
    {
      name: 'Northern Ireland',
      code: 'GB',
      dial_code: '+44',
      city: 'Belfast',
      continent: 'Europe',
    },
    {
      name: 'Northern Mariana Islands',
      code: 'MP',
      dial_code: '+1670',
      city: 'Garapan',
      continent: 'Oceania',
    },
    {
      name: 'Norway',
      code: 'NO',
      dial_code: '+47',
      city: 'Oslo',
      continent: 'Europe',
    },
    {
      name: 'Oman',
      code: 'OM',
      dial_code: '+968',
      city: 'Masqat',
      continent: 'Asia',
    },
    {
      name: 'Pakistan',
      code: 'PK',
      dial_code: '+92',
      city: 'Islamabad',
      continent: 'Asia',
    },
    {
      name: 'Palau',
      code: 'PW',
      dial_code: '+680',
      city: 'Koror',
      continent: 'Oceania',
    },
    {
      name: 'Palestine',
      code: 'PS',
      dial_code: '+970',
      city: 'Gaza',
      continent: 'Asia',
    },
    {
      name: 'Panama',
      code: 'PA',
      dial_code: '+507',
      city: 'Ciudad de Panam',
      continent: 'North America',
    },
    {
      name: 'Papua New Guinea',
      code: 'PG',
      dial_code: '+675',
      city: 'Port Moresby',
      continent: 'Oceania',
    },
    {
      name: 'Paraguay',
      code: 'PY',
      dial_code: '+595',
      city: 'Asunci',
      continent: 'South America',
    },
    {
      name: 'Peru',
      code: 'PE',
      dial_code: '+51',
      city: 'Lima',
      continent: 'South America',
    },
    {
      name: 'Philippines',
      code: 'PH',
      dial_code: '+63',
      city: 'Manila',
      continent: 'Asia',
    },
    {
      name: 'Pitcairn',
      code: 'PN',
      dial_code: '+64',
      city: 'Adamstown',
      continent: 'Oceania',
    },
    {
      name: 'Poland',
      code: 'PL',
      dial_code: '+48',
      city: 'Warszawa',
      continent: 'Europe',
    },
    {
      name: 'Portugal',
      code: 'PT',
      dial_code: '+351',
      city: 'Lisboa',
      continent: 'Europe',
    },
    {
      name: 'Puerto Rico',
      code: 'PR',
      dial_code: '+1939',
      city: 'San Juan',
      continent: 'North America',
    },
    {
      name: 'Qatar',
      code: 'QA',
      dial_code: '+974',
      city: 'Doha',
      continent: 'Asia',
    },
    {
      name: 'Reunion',
      code: 'RE',
      dial_code: '+262',
      city: 'Saint-Denis',
      continent: 'Africa',
    },
    {
      name: 'Romania',
      code: 'RO',
      dial_code: '+40',
      city: 'Bucuresti',
      continent: 'Europe',
    },
    {
      name: 'Russian Federation',
      code: 'RU',
      dial_code: '+7',
      city: 'Moscow',
      continent: 'Europe',
    },
    {
      name: 'Rwanda',
      code: 'RW',
      dial_code: '+250',
      city: 'Kigali',
      continent: 'Africa',
    },
    {
      name: 'Saint Helena',
      code: 'SH',
      dial_code: '+290',
      city: 'Jamestown',
      continent: 'Africa',
    },
    {
      name: 'Saint Kitts and Nevis',
      code: 'KN',
      dial_code: '+1869',
      city: 'Basseterre',
      continent: 'North America',
    },
    {
      name: 'Saint Lucia',
      code: 'LC',
      dial_code: '+1758',
      city: 'Castries',
      continent: 'North America',
    },
    {
      name: 'Saint Pierre and Miquelon',
      code: 'PM',
      dial_code: '+508',
      city: 'Saint-Pierre',
      continent: 'North America',
    },
    {
      name: 'Saint Vincent and the Grenadines',
      code: 'VC',
      dial_code: '+1784',
      city: 'Kingstown',
      continent: 'North America',
    },
    {
      name: 'Samoa',
      code: 'WS',
      dial_code: '+685',
      city: 'Apia',
      continent: 'Oceania',
    },
    {
      name: 'San Marino',
      code: 'SM',
      dial_code: '+378',
      city: 'San Marino',
      continent: 'Europe',
    },
    {
      name: 'Sao Tome and Principe',
      code: 'ST',
      dial_code: '+239',
      city: 'S',
      continent: 'Africa',
    },
    {
      name: 'Saudi Arabia',
      code: 'SA',
      dial_code: '+966',
      city: 'Riyadh',
      continent: 'Asia',
    },
    {
      name: 'Senegal',
      code: 'SN',
      dial_code: '+221',
      city: 'Dakar',
      continent: 'Africa',
    },
    {
      name: 'Serbia',
      code: 'RS',
      dial_code: '+381',
      city: 'Belgrade',
      continent: 'Europe',
    },
    {
      name: 'Seychelles',
      code: 'SC',
      dial_code: '+248',
      city: 'Victoria',
      continent: 'Africa',
    },
    {
      name: 'Sierra Leone',
      code: 'SL',
      dial_code: '+232',
      city: 'Freetown',
      continent: 'Africa',
    },
    {
      name: 'Singapore',
      code: 'SG',
      dial_code: '+65',
      city: 'Singapore',
      continent: 'Asia',
    },
    {
      name: 'Slovakia',
      code: 'SK',
      dial_code: '+421',
      city: 'Bratislava',
      continent: 'Europe',
    },
    {
      name: 'Slovenia',
      code: 'SI',
      dial_code: '+386',
      city: 'Ljubljana',
      continent: 'Europe',
    },
    {
      name: 'Solomon Islands',
      code: 'SB',
      dial_code: '+677',
      city: 'Honiara',
      continent: 'Oceania',
    },
    {
      name: 'Somalia',
      code: 'SO',
      dial_code: '+252',
      city: 'Mogadishu',
      continent: 'Africa',
    },
    {
      name: 'South Africa',
      code: 'ZA',
      dial_code: '+27',
      city: 'Pretoria',
      continent: 'Africa',
    },
    {
      name: 'South Georgia and the South Sandwich Islands',
      code: 'GS',
      dial_code: '+500',
      city: '',
      continent: 'Antarctica',
    },
    {
      name: 'South Korea',
      code: 'KR',
      dial_code: '+82',
      city: 'Seoul',
      continent: 'Asia',
    },
    {
      name: 'South Sudan',
      code: 'SS',
      dial_code: '+211',
      city: 'Juba',
      continent: 'Africa',
    },
    {
      name: 'Spain',
      code: 'ES',
      dial_code: '+34',
      city: 'Madrid',
      continent: 'Europe',
    },
    {
      name: 'Sri Lanka',
      code: 'LK',
      dial_code: '+94',
      city: 'Sri Jayawardenapura-Kotte',
      continent: 'Asia',
    },
    {
      name: 'Sudan',
      code: 'SD',
      dial_code: '+249',
      city: 'Khartum',
      continent: 'Africa',
    },
    {
      name: 'Suriname',
      code: 'SR',
      dial_code: '+597',
      city: 'Paramaribo',
      continent: 'South America',
    },
    {
      name: 'Svalbard and Jan Mayen',
      code: 'SJ',
      dial_code: '+47',
      city: 'Longyearbyen',
      continent: 'Europe',
    },
    {
      name: 'Swaziland',
      code: 'SZ',
      dial_code: '+268',
      city: 'Mbabane',
      continent: 'Africa',
    },
    {
      name: 'Sweden',
      code: 'SE',
      dial_code: '+46',
      city: 'Stockholm',
      continent: 'Europe',
    },
    {
      name: 'Switzerland',
      code: 'CH',
      dial_code: '+41',
      city: 'Bern',
      continent: 'Europe',
    },
    {
      name: 'Syria',
      code: 'SY',
      dial_code: '+963',
      city: 'Damascus',
      continent: 'Asia',
    },
    {
      name: 'Tajikistan',
      code: 'TJ',
      dial_code: '+992',
      city: 'Dushanbe',
      continent: 'Asia',
    },
    {
      name: 'Tanzania',
      code: 'TZ',
      dial_code: '+255',
      city: 'Dodoma',
      continent: 'Africa',
    },
    {
      name: 'Thailand',
      code: 'TH',
      dial_code: '+66',
      city: 'Bangkok',
      continent: 'Asia',
    },
    {
      name: 'The Democratic Republic of Congo',
      code: 'CD',
      dial_code: '+243',
      city: 'Kinshasa',
      continent: 'Africa',
    },
    {
      name: 'Timor-Leste',
      code: 'TL',
      dial_code: '+undefined',
    },
    {
      name: 'Togo',
      code: 'TG',
      dial_code: '+228',
      city: 'Lomé',
      continent: 'Africa',
    },
    {
      name: 'Tokelau',
      code: 'TK',
      dial_code: '+690',
      city: 'Fakaofo',
      continent: 'Oceania',
    },
    {
      name: 'Tonga',
      code: 'TO',
      dial_code: '+676',
      city: "Nuku'alofa",
      continent: 'Oceania',
    },
    {
      name: 'Trinidad and Tobago',
      code: 'TT',
      dial_code: '+1868',
      city: 'Port-of-Spain',
      continent: 'North America',
    },
    {
      name: 'Tunisia',
      code: 'TN',
      dial_code: '+216',
      city: 'Tunis',
      continent: 'Africa',
    },
    {
      name: 'Turkey',
      code: 'TR',
      dial_code: '+90',
      city: 'Ankara',
      continent: 'Asia',
    },
    {
      name: 'Turkmenistan',
      code: 'TM',
      dial_code: '+993',
      city: 'Ashgabat',
      continent: 'Asia',
    },
    {
      name: 'Turks and Caicos Islands',
      code: 'TC',
      dial_code: '+1649',
      city: 'Cockburn Town',
      continent: 'North America',
    },
    {
      name: 'Tuvalu',
      code: 'TV',
      dial_code: '+688',
      city: 'Funafuti',
      continent: 'Oceania',
    },
    {
      name: 'Uganda',
      code: 'UG',
      dial_code: '+256',
      city: 'Kampala',
      continent: 'Africa',
    },
    {
      name: 'Ukraine',
      code: 'UA',
      dial_code: '+380',
      city: 'Kyiv',
      continent: 'Europe',
    },
    {
      name: 'United Arab Emirates',
      code: 'AE',
      dial_code: '+971',
      city: 'Abu Dhabi',
      continent: 'Asia',
    },
    {
      name: 'United Kingdom',
      code: 'UK',
      dial_code: '+44',
      city: 'London',
      continent: 'Europe',
    },
    {
      name: 'United States',
      code: 'US',
      dial_code: '+1',
      city: 'Washington',
      continent: 'North America',
    },
    {
      name: 'United States Minor Outlying Islands',
      code: 'UM',
      dial_code: '+1',
      city: '',
      continent: 'Oceania',
    },
    {
      name: 'Uruguay',
      code: 'UY',
      dial_code: '+598',
      city: 'Montevideo',
      continent: 'South America',
    },
    {
      name: 'Uzbekistan',
      code: 'UZ',
      dial_code: '+998',
      city: 'Toskent',
      continent: 'Asia',
    },
    {
      name: 'Vanuatu',
      code: 'VU',
      dial_code: '+678',
      city: 'Port-Vila',
      continent: 'Oceania',
    },
    {
      name: 'Venezuela',
      code: 'VE',
      dial_code: '+58',
      city: 'Caracas',
      continent: 'South America',
    },
    {
      name: 'Vietnam',
      code: 'VN',
      dial_code: '+84',
      city: 'Hanoi',
      continent: 'Asia',
    },
    {
      name: 'Virgin Islands, British',
      code: 'VG',
      dial_code: '+1',
      city: 'Road Town',
      continent: 'North America',
    },
    {
      name: 'Virgin Islands, U.S.',
      code: 'VI',
      dial_code: '+1',
      city: 'Charlotte Amalie',
      continent: 'North America',
    },
    {
      name: 'Wallis and Futuna',
      code: 'WF',
      dial_code: '+681',
      city: 'Mata-Utu',
      continent: 'Oceania',
    },
    {
      name: 'Western Sahara',
      code: 'EH',
      dial_code: '+212',
      city: 'El-Aai',
      continent: 'Africa',
    },
    {
      name: 'Yemen',
      code: 'YE',
      dial_code: '+967',
      city: 'Sanaa',
      continent: 'Asia',
    },
    {
      name: 'Zambia',
      code: 'ZM',
      dial_code: '+260',
      city: 'Lusaka',
      continent: 'Africa',
    },
    {
      name: 'Zimbabwe',
      code: 'ZW',
      dial_code: '+263',
      city: 'Harare',
      continent: 'Africa',
    },
    {
      name: 'England',
      code: 'UK',
      dial_code: '+44',
      city: 'London',
      continent: 'Europe',
    },
    {
      name: 'Scotland',
      code: 'UK',
      dial_code: '+44',
      city: 'Edinburgh',
      continent: 'Europe',
    },
    {
      name: 'Wales',
      code: 'UK',
      dial_code: '+44',
      city: 'Cardiff',
      continent: 'Europe',
    },
  ];

  isValidNumber(input: string): boolean {
    return parsePhoneNumber(input)?.isValid() || false;
  }

  parsePhoneNumber(input: string): any {
    const parsed = parsePhoneNumber(input);
    if (!parsed || !parsed.isValid()) {
      return null;
    }
    return {
      ...parsed,
      number: parsed.nationalNumber,
    };
  }
}
